include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false

linter:
  rules:
    - avoid_print: false
    - prefer_const_constructors: false
    - prefer_const_literals_to_create_immutables: false
    - deprecated_member_use: false