name: shortsy_app
description: "Shortsy - Short Video App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.1.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.0.0
  camera: ^0.10.5+9
  video_player: ^2.8.6
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0
  share_plus: ^7.2.1
  connectivity_plus: ^6.0.3
  flutter_cache_manager: ^3.3.1
  wakelock_plus: ^1.2.5
  livekit_client: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1
  image: ^4.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/branding/logo.png
    - assets/branding/icon_foreground_padded.png

# Конфигурация сплэш-экрана
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#0A0A0A"
  image: assets/branding/logo.png
  image_dark: assets/branding/logo.png
  android_gravity: center
  ios_content_mode: center
  # подпись под логотипом
  branding: assets/branding/splash_branding_light.png
  branding_dark: assets/branding/splash_branding_dark.png
  branding_mode: bottom
  android_12:
    color: "#FFFFFF"
    color_dark: "#0A0A0A"
    image: assets/branding/logo.png
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#0A0A0A"
  android: true
  ios: true
  web: false
  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/branding/logo.png
  adaptive_icon_foreground: assets/branding/icon_foreground_padded.png
  adaptive_icon_background: "#0A0A0A"
  remove_alpha_ios: true
